// internal/infrastructure/jsonstore.go
package infrastructure

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"gemini-bridge/internal/domain/model"
)

// JsonMetadataStore はport.MetadataStoreのJSON実装。
// メタデータをJSONファイルとしてローカルに出力する。
type JsonMetadataStore struct {
	baseDir string
}

func NewJsonMetadataStore(baseDir string) *JsonMetadataStore {
	return &JsonMetadataStore{baseDir: baseDir}
}

func (s *JsonMetadataStore) SavePostMeta(meta model.PostMeta) error {
	path := filepath.Join(s.baseDir, "posts", meta.Slug, "meta.json")
	return s.writeJSON(path, meta)
}

func (s *JsonMetadataStore) SaveSiteIndex(posts []model.PostMeta) error {
	// KVにロードするインデックスJSON
	indexPath := filepath.Join(s.baseDir, "index.json")
	if err := s.writeJSON(indexPath, posts); err != nil {
		return err
	}

	// D1シード用SQL生成
	seedPath := filepath.Join(s.baseDir, "seed.sql")
	return s.writeSeedSQL(seedPath, posts)
}

func (s *JsonMetadataStore) writeJSON(path string, v interface{}) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}

	data, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return err
	}

	return os.WriteFile(path, data, 0644)
}

// writeSeedSQL はD1のシード用INSERT文を生成する。
func (s *JsonMetadataStore) writeSeedSQL(path string, posts []model.PostMeta) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}

	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	// テーブルが存在しない場合のみ作成
	fmt.Fprintln(f, "-- Auto-generated by gemini-bridge SSG")
	fmt.Fprintln(f, "DELETE FROM posts;")
	fmt.Fprintln(f)

	for _, post := range posts {
		tagsJSON, _ := json.Marshal(post.Tags)
		fmt.Fprintf(f,
			"INSERT INTO posts (id, slug, title, published_at, word_count, language, tags, gemtext_hash) "+
				"VALUES ('%s', '%s', '%s', '%s', %d, '%s', '%s', '%s');\n",
			post.Slug,
			post.Slug,
			escapeSQL(post.Title),
			post.Date.Format("2006-01-02T15:04:05Z"),
			post.WordCount,
			post.Language,
			escapeSQL(string(tagsJSON)),
			post.GemtextHash,
		)
	}

	return nil
}

func escapeSQL(s string) string {
	// シングルクォートのエスケープ
	result := make([]byte, 0, len(s))
	for i := 0; i < len(s); i++ {
		if s[i] == '\'' {
			result = append(result, '\'', '\'')
		} else {
			result = append(result, s[i])
		}
	}
	return string(result)
}
